# Base Lambda image (Python 3.13)
FROM public.ecr.aws/lambda/python:3.13

# Install system dependencies
RUN yum install -y gcc g++ make && yum clean all

# Copy requirements
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Lambda handler code
COPY kinesis_lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the handler
CMD ["kinesis_lambda_function.lambda_handler"]
